# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.4

# too annoying and petty to enable ;)
#      - name: Verify formatting
#        run: deno fmt --check

      - name: Run linter
        run: deno lint

# a bit overwhelming for now ;)
#      - name: Run tests
#        run: deno test -A
